version: '2.1'
services:
   service:
     image: kvalitetsit/fut-patient-bff:latest
     environment:
      - usercontext_header_name=X-Test-Auth

      - userattributes_role_key=UserRoles
      - userattributes_org_key=organisation

      - userrole_admin_values=adminrole
      - userrole_user_values=userrole1,userrole2
      - userrole_monitor_values=monitorrole
      - userrole_provisioner_values=provisionerrole
     depends_on:
      mariadb:
       condition: service_healthy
     ports: 
      - 8080:8080
   documenatation-and-test:
     image: kvalitetsit/fut-patient-bff-documentation:latest
     environment:
      - BASE_URL=/test
      - 'SERVER_URLS=[{"url": "http://localhost:8080", "name": "Service"}]'
     ports:
      - 80:8080
